
all_dishes = [
    {'name': '매운떡볶이', 'tags': ['spicy', 'korean']},
    {'name': '매운갈비찜', 'tags': ['spicy']},
    {'name': '매운짬뽕', 'tags': ['spicy', 'foreign']},
    {'name': '불닭볶음면', 'tags': ['spicy']},
    {'name': '매운닭발', 'tags': ['spicy']},
    {'name': '매운짜장면', 'tags': ['spicy', 'chinese']},
    {'name': '매운쭈꾸미', 'tags': ['spicy', 'korean']},
    {'name': '매운비빔면', 'tags': ['spicy']},
    {'name': '매운닭도리탕', 'tags': ['spicy', 'korean']},
    {'name': '매운고추잡채', 'tags': ['spicy', 'chinese']},

    {'name': '닭죽', 'tags': ['mild', 'korean']},
    {'name': '계란찜', 'tags': ['mild', 'korean']},
    {'name': '미역국', 'tags': ['mild', 'korean']},
    {'name': '우유라면', 'tags': ['mild']},
    {'name': '순두부찌개', 'tags': ['mild', 'korean']},
    {'name': '크림리조또', 'tags': ['mild', 'western']},
    {'name': '소고기죽', 'tags': ['mild', 'korean']},
    {'name': '오트밀죽', 'tags': ['mild']},
    {'name': '양송이스프', 'tags': ['mild', 'western']},
    {'name': '두부덮밥', 'tags': ['mild', 'korean']},

    {'name': '부리또', 'tags': ['adventurous', 'foreign']},
    {'name': '쌀국수', 'tags': ['adventurous', 'foreign']},
    {'name': '나시고렝', 'tags': ['adventurous', 'foreign']},
    {'name': '에그인헬', 'tags': ['adventurous', 'western']},
    {'name': '카레우동', 'tags': ['adventurous', 'japanese']},
    {'name': '꿔바로우', 'tags': ['adventurous', 'chinese']},
    {'name': '파인애플볶음밥', 'tags': ['adventurous', 'thai']},
    {'name': '타코', 'tags': ['adventurous', 'mexican']},
    {'name': '이국적타코야끼', 'tags': ['adventurous', 'japanese']},
    {'name': '비빔밥', 'tags': ['adventurous', 'korean']},

    {'name': '김치찌개', 'tags': ['safe', 'korean']},
    {'name': '된장찌개', 'tags': ['safe', 'korean']},
    {'name': '갈비탕', 'tags': ['safe', 'korean']},
    {'name': '제육볶음', 'tags': ['safe', 'korean']},
    {'name': '삼겹살', 'tags': ['safe', 'korean']},
    {'name': '오징어볶음', 'tags': ['safe', 'korean']},
    {'name': '잡채', 'tags': ['safe', 'korean']},
    {'name': '불고기', 'tags': ['safe', 'korean']},
    {'name': '감자탕', 'tags': ['safe', 'korean']},
    {'name': '콩나물국밥', 'tags': ['safe', 'korean']},

    {'name': '토스트', 'tags': ['mild', 'snack']},
    {'name': '라면', 'tags': ['safe']},
    {'name': '오므라이스', 'tags': ['safe', 'fusion']},
    {'name': '카레라이스', 'tags': ['safe', 'fusion']},
    {'name': '떡국', 'tags': ['safe', 'korean']},
    {'name': '소고기무국', 'tags': ['safe', 'korean']},
    {'name': '잡채밥', 'tags': ['safe', 'korean']}
]